# Generated by Django 4.2.5 on 2023-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Phone'),
        ),
    ]
